project_id = "xeyippgcoqfskcmqzazx"

[functions.create-booking]
verify_jwt = false

[functions.request-photo-quote]
verify_jwt = false

[functions.booked-slots]
verify_jwt = false

[functions.validate-discount]
verify_jwt = false

[functions.complete-booking]
verify_jwt = true

[functions.rut-booking-details]
verify_jwt = false

[functions.submit-rut]
verify_jwt = false

[functions.admin-rut-details]
verify_jwt = true

[functions.manage-booking]
verify_jwt = false

[functions.send-booking-reminders]
verify_jwt = false
