-- Additive CRM and communication foundation for the admin redesign.
-- This migration deliberately does not backfill, rewrite or delete bookings,
-- and it does not change the existing Swish, payment or encrypted RUT flows.

set local search_path = pg_catalog, public, extensions;

create extension if not exists pgcrypto with schema extensions;

create table if not exists public.customers (
  id uuid primary key default extensions.gen_random_uuid(),
  display_name text not null check (char_length(btrim(display_name)) between 1 and 160),
  email text,
  phone text,
  customer_type text not null default 'private' check (customer_type in ('private', 'business')),
  lifecycle_status text not null default 'new' check (lifecycle_status in ('new', 'active', 'returning', 'inactive', 'paused', 'archived')),
  last_booking_at timestamp with time zone,
  next_booking_at timestamp with time zone,
  last_contacted_at timestamp with time zone,
  next_follow_up_at timestamp with time zone,
  review_status text not null default 'not_requested' check (review_status in ('not_requested', 'scheduled', 'request_sent', 'reminder_sent', 'received', 'do_not_contact')),
  review_requested_at timestamp with time zone,
  review_reminder_sent_at timestamp with time zone,
  review_received_at timestamp with time zone,
  automated_communication_paused boolean not null default false,
  communication_preferences jsonb not null default '{"service":true,"review":true,"marketing":false}'::jsonb,
  internal_notes text,
  assigned_admin_user_id uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint customers_review_dates_order check (
    review_reminder_sent_at is null or review_requested_at is null or review_reminder_sent_at >= review_requested_at
  )
);

create unique index if not exists customers_normalized_email_idx
  on public.customers (lower(btrim(email))) where email is not null and btrim(email) <> '';
create index if not exists customers_phone_idx on public.customers (phone) where phone is not null;
create index if not exists customers_follow_up_idx on public.customers (next_follow_up_at) where next_follow_up_at is not null;
create index if not exists customers_lifecycle_idx on public.customers (lifecycle_status, last_booking_at desc);

create table if not exists public.customer_addresses (
  id uuid primary key default extensions.gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  label text,
  address_line text not null check (char_length(btrim(address_line)) between 1 and 500),
  postal_code text,
  city text,
  is_primary boolean not null default false,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create unique index if not exists customer_addresses_one_primary_idx
  on public.customer_addresses (customer_id) where is_primary;

create table if not exists public.customer_tags (
  id uuid primary key default extensions.gen_random_uuid(),
  name text not null check (char_length(btrim(name)) between 1 and 50),
  color text,
  created_at timestamp with time zone not null default now()
);
create unique index if not exists customer_tags_name_idx on public.customer_tags (lower(btrim(name)));

create table if not exists public.customer_tag_links (
  customer_id uuid not null references public.customers(id) on delete cascade,
  tag_id uuid not null references public.customer_tags(id) on delete cascade,
  created_at timestamp with time zone not null default now(),
  primary key (customer_id, tag_id)
);

create table if not exists public.customer_notes (
  id bigint generated by default as identity primary key,
  customer_id uuid not null references public.customers(id) on delete cascade,
  booking_id text,
  note text not null check (char_length(btrim(note)) between 1 and 5000),
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create index if not exists customer_notes_customer_idx on public.customer_notes (customer_id, created_at desc);

create table if not exists public.email_templates (
  id uuid primary key default extensions.gen_random_uuid(),
  template_key text not null check (template_key ~ '^[a-z0-9_]{3,80}$'),
  name text not null,
  subject text not null check (char_length(subject) between 1 and 300),
  html_body text not null,
  text_body text not null,
  allowed_variables text[] not null default '{}',
  version integer not null default 1 check (version > 0),
  active boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  unique (template_key, version)
);

create table if not exists public.automation_rules (
  id uuid primary key default extensions.gen_random_uuid(),
  rule_key text not null unique check (rule_key ~ '^[a-z0-9_]{3,80}$'),
  name text not null,
  trigger_type text not null,
  delay_seconds integer not null default 0 check (delay_seconds between 0 and 31557600),
  conditions jsonb not null default '{}'::jsonb,
  action_type text not null default 'send_email' check (action_type in ('send_email', 'create_task')),
  email_template_id uuid references public.email_templates(id) on delete restrict,
  stop_conditions jsonb not null default '{}'::jsonb,
  active boolean not null default false,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint automation_email_template_required check (action_type <> 'send_email' or email_template_id is not null)
);

create table if not exists public.scheduled_messages (
  id uuid primary key default extensions.gen_random_uuid(),
  customer_id uuid references public.customers(id) on delete cascade,
  booking_id text,
  automation_id uuid references public.automation_rules(id) on delete set null,
  email_template_id uuid references public.email_templates(id) on delete restrict,
  template_version integer,
  message_type text not null,
  recipient_email text not null,
  scheduled_for timestamp with time zone not null,
  status text not null default 'scheduled' check (status in ('scheduled', 'sending', 'sent', 'failed', 'skipped', 'cancelled', 'paused')),
  idempotency_key text not null check (char_length(idempotency_key) between 16 and 200),
  attempt_count integer not null default 0 check (attempt_count between 0 and 20),
  provider_message_id text,
  last_error_code text,
  stopped_reason text,
  trigger_snapshot jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  sent_at timestamp with time zone,
  unique (idempotency_key)
);
create index if not exists scheduled_messages_due_idx
  on public.scheduled_messages (scheduled_for) where status = 'scheduled';
create index if not exists scheduled_messages_customer_idx
  on public.scheduled_messages (customer_id, created_at desc);
create unique index if not exists scheduled_messages_provider_id_idx
  on public.scheduled_messages (provider_message_id) where provider_message_id is not null;

create table if not exists public.communication_events (
  id bigint generated by default as identity primary key,
  customer_id uuid references public.customers(id) on delete cascade,
  booking_id text,
  scheduled_message_id uuid references public.scheduled_messages(id) on delete set null,
  event_type text not null,
  channel text not null default 'system' check (channel in ('email', 'phone', 'sms', 'system', 'note')),
  status text not null check (status in ('planned', 'sent', 'failed', 'skipped', 'cancelled', 'paused', 'completed')),
  subject text,
  summary text,
  reason_code text,
  metadata jsonb not null default '{}'::jsonb,
  actor_user_id uuid references auth.users(id) on delete set null,
  occurred_at timestamp with time zone not null default now()
);
create index if not exists communication_events_customer_idx
  on public.communication_events (customer_id, occurred_at desc);
create index if not exists communication_events_booking_idx
  on public.communication_events (booking_id, occurred_at desc) where booking_id is not null;

create table if not exists public.automation_runs (
  id bigint generated by default as identity primary key,
  automation_id uuid not null references public.automation_rules(id) on delete cascade,
  customer_id uuid references public.customers(id) on delete cascade,
  booking_id text,
  idempotency_key text not null,
  outcome text not null check (outcome in ('scheduled', 'executed', 'stopped', 'skipped', 'failed')),
  trigger_data jsonb not null default '{}'::jsonb,
  stop_reason text,
  created_at timestamp with time zone not null default now(),
  executed_at timestamp with time zone,
  unique (automation_id, idempotency_key)
);
create index if not exists automation_runs_customer_idx
  on public.automation_runs (customer_id, created_at desc);

create table if not exists public.follow_up_tasks (
  id uuid primary key default extensions.gen_random_uuid(),
  customer_id uuid not null references public.customers(id) on delete cascade,
  booking_id text,
  reason text not null,
  recommended_action text not null,
  due_at timestamp with time zone not null,
  assigned_admin_user_id uuid references auth.users(id) on delete set null,
  status text not null default 'open' check (status in ('open', 'completed', 'snoozed', 'paused', 'cancelled')),
  snoozed_until timestamp with time zone,
  automation_id uuid references public.automation_rules(id) on delete set null,
  idempotency_key text,
  completed_at timestamp with time zone,
  completed_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now()
);
create unique index if not exists follow_up_tasks_idempotency_idx
  on public.follow_up_tasks (idempotency_key) where idempotency_key is not null;
create index if not exists follow_up_tasks_due_idx
  on public.follow_up_tasks (status, due_at) where status in ('open', 'snoozed');

create table if not exists public.admin_activity_log (
  id bigint generated by default as identity primary key,
  actor_user_id uuid references auth.users(id) on delete set null,
  action text not null,
  object_type text not null,
  object_id text not null,
  previous_value jsonb,
  new_value jsonb,
  automation_id uuid references public.automation_rules(id) on delete set null,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamp with time zone not null default now()
);
comment on table public.admin_activity_log is
  'Append-only adminlogg. Personnummer, RUT-krypteringsmaterial och hemliga token får aldrig lagras här.';
create index if not exists admin_activity_log_object_idx
  on public.admin_activity_log (object_type, object_id, created_at desc);

create or replace function private.set_admin_crm_updated_at()
returns trigger
language plpgsql
set search_path = pg_catalog
as $$
begin
  new.updated_at := now();
  return new;
end;
$$;
revoke all on function private.set_admin_crm_updated_at() from public, anon, authenticated;

do $triggers$
declare
  table_name text;
  trigger_name text;
begin
  foreach table_name in array array['customers', 'customer_addresses', 'customer_notes', 'email_templates', 'automation_rules', 'scheduled_messages', 'follow_up_tasks']
  loop
    trigger_name := 'set_' || table_name || '_updated_at';
    execute format('drop trigger if exists %I on public.%I', trigger_name, table_name);
    execute format('create trigger %I before update on public.%I for each row execute function private.set_admin_crm_updated_at()', trigger_name, table_name);
  end loop;
end;
$triggers$;

do $rls$
declare
  table_name text;
begin
  foreach table_name in array array[
    'customers', 'customer_addresses', 'customer_tags', 'customer_tag_links',
    'customer_notes', 'email_templates', 'automation_rules', 'scheduled_messages',
    'communication_events', 'automation_runs', 'follow_up_tasks', 'admin_activity_log'
  ]
  loop
    execute format('alter table public.%I enable row level security', table_name);
    execute format('revoke all on table public.%I from public, anon', table_name);
  end loop;
end;
$rls$;

-- Editable admin-owned records.
do $editable_policies$
declare
  table_name text;
  policy_name text;
begin
  foreach table_name in array array[
    'customers', 'customer_addresses', 'customer_tags', 'customer_tag_links',
    'customer_notes', 'email_templates', 'automation_rules', 'scheduled_messages',
    'follow_up_tasks'
  ]
  loop
    policy_name := table_name || '_booking_admins_manage';
    execute format('grant select, insert, update, delete on table public.%I to authenticated', table_name);
    execute format('drop policy if exists %I on public.%I', policy_name, table_name);
    execute format('create policy %I on public.%I for all to authenticated using (private.is_booking_admin()) with check (private.is_booking_admin())', policy_name, table_name);
  end loop;
end;
$editable_policies$;

-- Append-only audit/timeline records: browser admins may read and append, but
-- never rewrite history. Service-role workers retain their normal bypass.
do $append_only_policies$
declare
  table_name text;
  read_policy text;
  insert_policy text;
begin
  foreach table_name in array array['communication_events', 'automation_runs', 'admin_activity_log']
  loop
    read_policy := table_name || '_booking_admins_read';
    insert_policy := table_name || '_booking_admins_append';
    execute format('grant select, insert on table public.%I to authenticated', table_name);
    execute format('revoke update, delete on table public.%I from authenticated', table_name);
    execute format('drop policy if exists %I on public.%I', read_policy, table_name);
    execute format('drop policy if exists %I on public.%I', insert_policy, table_name);
    execute format('create policy %I on public.%I for select to authenticated using (private.is_booking_admin())', read_policy, table_name);
    execute format('create policy %I on public.%I for insert to authenticated with check (private.is_booking_admin())', insert_policy, table_name);
  end loop;
end;
$append_only_policies$;

grant usage, select on sequence public.customer_notes_id_seq to authenticated;
grant usage, select on sequence public.communication_events_id_seq to authenticated;
grant usage, select on sequence public.automation_runs_id_seq to authenticated;
grant usage, select on sequence public.admin_activity_log_id_seq to authenticated;

-- Safe presets are inactive until templates are reviewed and explicitly
-- attached. No automatic communication begins merely by running migration.
insert into public.automation_rules (
  rule_key, name, trigger_type, delay_seconds, conditions, action_type,
  email_template_id, stop_conditions, active
)
select preset.rule_key, preset.name, preset.trigger_type, preset.delay_seconds,
  preset.conditions, 'create_task', null, preset.stop_conditions, false
from (values
  ('thank_after_job', 'Tack efter utfört jobb', 'booking_completed', 0, '{"email_required":true}'::jsonb, '{"communication_paused":true,"unsubscribed":true}'::jsonb),
  ('review_request', 'Recensionsförfrågan', 'booking_closed', 172800, '{"review_status":"not_requested"}'::jsonb, '{"review_received":true,"request_already_sent":true,"communication_paused":true,"unsubscribed":true}'::jsonb),
  ('review_reminder', 'Påminnelse om recension', 'review_request_sent', 604800, '{"review_received":false,"reminder_already_sent":false}'::jsonb, '{"review_received":true,"delivery_failed":true,"communication_paused":true,"unsubscribed":true}'::jsonb),
  ('customer_reactivation', 'Återaktivering av tidigare kund', 'months_since_last_booking', 0, '{"months":6,"no_upcoming_booking":true}'::jsonb, '{"new_booking":true,"recent_similar_message":true,"communication_paused":true,"unsubscribed":true}'::jsonb),
  ('seasonal_reminder', 'Årlig eller säsongsbaserad påminnelse', 'months_since_last_booking', 0, '{"months":11,"no_upcoming_booking":true}'::jsonb, '{"new_booking":true,"recent_rebooking_message":true,"communication_paused":true,"unsubscribed":true}'::jsonb),
  ('quote_follow_up', 'Uppföljning efter offert eller manuell kontakt', 'manual_contact_recorded', 259200, '{"no_booking":true,"task_incomplete":true}'::jsonb, '{"new_booking":true,"task_completed":true,"communication_paused":true}'::jsonb)
) as preset(rule_key, name, trigger_type, delay_seconds, conditions, stop_conditions)
on conflict (rule_key) do nothing;
