create table if not exists public.booking_invitations (
  id bigint generated by default as identity primary key,
  email text not null,
  booking_date date not null,
  token_hash text not null unique,
  status text not null default 'active',
  expires_at timestamp with time zone not null,
  sent_at timestamp with time zone,
  completed_at timestamp with time zone,
  cancelled_at timestamp with time zone,
  booking_id text,
  created_by uuid references auth.users(id) on delete set null,
  created_at timestamp with time zone not null default now(),
  updated_at timestamp with time zone not null default now(),
  constraint booking_invitations_email_length check (char_length(email) between 3 and 254),
  constraint booking_invitations_token_hash_format check (token_hash ~ '^[0-9a-f]{64}$'),
  constraint booking_invitations_status_check check (status in ('active', 'completed', 'cancelled', 'expired'))
);

create or replace function public.is_booking_invitation_admin()
returns boolean
language sql
stable
security invoker
set search_path = pg_catalog, public, private
as $$
  select private.is_booking_admin();
$$;

revoke all on function public.is_booking_invitation_admin() from public, anon;
grant execute on function public.is_booking_invitation_admin() to authenticated;

alter table public.booking_invitations enable row level security;
alter table public.booking_invitations force row level security;

revoke all on table public.booking_invitations from public, anon, authenticated;
revoke all on sequence public.booking_invitations_id_seq from public, anon, authenticated;
grant select, insert, update, delete on table public.booking_invitations to service_role;
grant usage, select on sequence public.booking_invitations_id_seq to service_role;

comment on table public.booking_invitations is
  'Adminskapade bokningsinbjudningar som reserverar kapacitet tills kunden slutför eller inbjudningen löper ut.';
comment on column public.booking_invitations.token_hash is
  'SHA-256-hash av engångstoken. Rå token sparas aldrig i databasen.';

create index if not exists booking_invitations_active_date_idx
  on public.booking_invitations (booking_date, expires_at)
  where status = 'active';

create index if not exists booking_invitations_created_at_idx
  on public.booking_invitations (created_at desc);

create or replace function private.enforce_booking_invitation_capacity()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  allowed_capacity integer;
  used_capacity integer;
begin
  new.email := lower(trim(new.email));
  new.updated_at := now();

  if new.status <> 'active' or new.expires_at <= now() then
    return new;
  end if;

  allowed_capacity := coalesce((
    select 1 + extra_bookings
    from public.booking_capacity_overrides
    where booking_date = new.booking_date
  ), 1);

  used_capacity := (
    select count(*)
    from public.bookings
    where booking_date = new.booking_date
      and status in ('pending', 'confirmed')
  ) + (
    select count(*)
    from public.booking_invitations
    where booking_date = new.booking_date
      and status = 'active'
      and expires_at > now()
      and id is distinct from new.id
  );

  if used_capacity >= allowed_capacity then
    raise exception 'booking_date_unavailable' using errcode = 'unique_violation';
  end if;

  return new;
end;
$$;

revoke all on function private.enforce_booking_invitation_capacity() from public, anon, authenticated, service_role;

drop trigger if exists enforce_booking_invitation_capacity on public.booking_invitations;
create trigger enforce_booking_invitation_capacity
before insert or update of booking_date, status, expires_at, email
on public.booking_invitations
for each row execute function private.enforce_booking_invitation_capacity();

create or replace function private.enforce_booking_day_capacity()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  allowed_capacity integer;
  used_capacity integer;
begin
  if new.status not in ('pending', 'confirmed') or new.booking_date < date '2026-07-15' then
    return new;
  end if;

  allowed_capacity := coalesce((
    select 1 + extra_bookings
    from public.booking_capacity_overrides
    where booking_date = new.booking_date
  ), 1);

  used_capacity := (
    select count(*)
    from public.bookings
    where booking_date = new.booking_date
      and status in ('pending', 'confirmed')
      and id is distinct from new.id
  ) + (
    select count(*)
    from public.booking_invitations
    where booking_date = new.booking_date
      and status = 'active'
      and expires_at > now()
  );

  if used_capacity >= allowed_capacity then
    raise exception 'booking_date_unavailable' using errcode = 'unique_violation';
  end if;

  return new;
end;
$$;

drop trigger if exists enforce_booking_day_capacity on public.bookings;
create trigger enforce_booking_day_capacity
before insert or update of booking_date, status on public.bookings
for each row execute function private.enforce_booking_day_capacity();

create or replace function public.finalize_booking_invitation(
  p_token_hash text,
  p_booking_id text
)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  target_invitation public.booking_invitations%rowtype;
  target_booking public.bookings%rowtype;
begin
  if p_token_hash is null
    or p_token_hash !~ '^[0-9a-f]{64}$'
    or p_booking_id is null
    or char_length(p_booking_id) not between 1 and 80
  then
    return false;
  end if;

  select * into target_invitation
  from public.booking_invitations
  where token_hash = p_token_hash
  for update;

  select * into target_booking
  from public.bookings
  where id::text = p_booking_id
  for update;

  if target_invitation.id is null
    or target_invitation.status <> 'active'
    or target_invitation.expires_at <= now()
    or target_booking.id is null
    or target_booking.status <> 'awaiting_confirmation'
    or target_booking.booking_date <> target_invitation.booking_date
    or lower(target_booking.email) <> lower(target_invitation.email)
  then
    return false;
  end if;

  update public.booking_invitations
  set status = 'completed',
      completed_at = now(),
      booking_id = target_booking.id::text,
      updated_at = now()
  where id = target_invitation.id;

  update public.bookings
  set status = 'pending',
      email_confirmed_at = coalesce(email_confirmed_at, now()),
      email_confirmation_expires_at = null
  where id::text = target_booking.id::text;

  return true;
end;
$$;

revoke all on function public.finalize_booking_invitation(text, text) from public, anon, authenticated;
grant execute on function public.finalize_booking_invitation(text, text) to service_role;
