create table if not exists public.clarity_analytics_snapshots (
  id bigint generated by default as identity primary key,
  snapshot_date date not null,
  period_start timestamp with time zone not null,
  period_end timestamp with time zone not null,
  fetched_at timestamp with time zone not null default now(),
  project_id text not null,
  dimension_key text not null,
  dimensions text[] not null,
  metrics jsonb not null,
  row_count integer not null default 0 check (row_count >= 0 and row_count <= 1000),
  schema_version integer not null default 1,
  constraint clarity_snapshot_period_valid check (period_end > period_start),
  constraint clarity_snapshot_dimensions_valid check (cardinality(dimensions) between 1 and 3),
  constraint clarity_snapshot_unique unique (snapshot_date, project_id, dimension_key)
);

comment on table public.clarity_analytics_snapshots is
  'Aggregerade Clarity Data Export-snapshots. Inga tokens, inspelningar eller direkt identifierande kunduppgifter.';

alter table public.clarity_analytics_snapshots enable row level security;
alter table public.clarity_analytics_snapshots force row level security;
revoke all on table public.clarity_analytics_snapshots from public, anon, authenticated;
grant select on table public.clarity_analytics_snapshots to authenticated;

drop policy if exists "booking admins can read clarity snapshots" on public.clarity_analytics_snapshots;
create policy "booking admins can read clarity snapshots"
on public.clarity_analytics_snapshots
for select
to authenticated
using (private.is_booking_admin());

create table if not exists public.clarity_api_daily_usage (
  usage_date date primary key,
  reserved_calls smallint not null default 0 check (reserved_calls between 0 and 9),
  updated_at timestamp with time zone not null default now()
);

alter table public.clarity_api_daily_usage enable row level security;
alter table public.clarity_api_daily_usage force row level security;
revoke all on table public.clarity_api_daily_usage from public, anon, authenticated;

create or replace function public.reserve_clarity_api_calls(p_call_count integer)
returns boolean
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
declare
  stockholm_date date := (now() at time zone 'Europe/Stockholm')::date;
  current_count integer;
begin
  if p_call_count < 1 or p_call_count > 3 then
    return false;
  end if;

  perform pg_advisory_xact_lock(hashtext('clarity-api-daily-budget'));
  select reserved_calls into current_count
  from public.clarity_api_daily_usage
  where usage_date = stockholm_date;

  current_count := coalesce(current_count, 0);
  if current_count + p_call_count > 9 then
    return false;
  end if;

  insert into public.clarity_api_daily_usage (usage_date, reserved_calls, updated_at)
  values (stockholm_date, current_count + p_call_count, now())
  on conflict (usage_date) do update
    set reserved_calls = excluded.reserved_calls,
        updated_at = excluded.updated_at;
  return true;
end;
$$;

revoke all on function public.reserve_clarity_api_calls(integer) from public, anon, authenticated;
grant execute on function public.reserve_clarity_api_calls(integer) to service_role;

create or replace function public.is_clarity_analytics_admin()
returns boolean
language sql
stable
security invoker
set search_path = pg_catalog, public, private
as $$
  select private.is_booking_admin();
$$;

revoke all on function public.is_clarity_analytics_admin() from public, anon;
grant execute on function public.is_clarity_analytics_admin() to authenticated;

create or replace function private.purge_old_clarity_analytics()
returns void
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  delete from public.clarity_analytics_snapshots
  where snapshot_date < (now() at time zone 'Europe/Stockholm')::date - 270;

  delete from public.clarity_api_daily_usage
  where usage_date < (now() at time zone 'Europe/Stockholm')::date - 14;
end;
$$;

revoke all on function private.purge_old_clarity_analytics() from public, anon, authenticated, service_role;

do $schedule$
begin
  if exists (select 1 from pg_extension where extname = 'pg_cron') then
    if not exists (select 1 from cron.job where jobname = 'purge-old-clarity-analytics') then
      perform cron.schedule(
        'purge-old-clarity-analytics',
        '17 3 * * *',
        'select private.purge_old_clarity_analytics();'
      );
    end if;

    if not exists (select 1 from pg_extension where extname = 'pg_net') then
      execute 'create extension if not exists pg_net';
    end if;

    if not exists (select 1 from cron.job where jobname = 'import-clarity-analytics') then
      perform cron.schedule(
        'import-clarity-analytics',
        '12 * * * *',
        $command$
          select net.http_post(
            url := 'https://xeyippgcoqfskcmqzazx.supabase.co/functions/v1/clarity-analytics',
            headers := jsonb_build_object(
              'Content-Type', 'application/json',
              'apikey', 'sb_publishable_MUKxAwv0vNXDrcgumq81fQ_Uvx4eOuq',
              'x-clarity-cron-secret', (
                select decrypted_secret
                from vault.decrypted_secrets
                where name = 'clarity_cron_secret'
                limit 1
              )
            ),
            body := '{"action":"scheduled-import"}'::jsonb,
            timeout_milliseconds := 120000
          );
        $command$
      );
    end if;
  end if;
end;
$schedule$;

do $verify$
begin
  if has_table_privilege('anon', 'public.clarity_analytics_snapshots', 'SELECT')
    or has_table_privilege('anon', 'public.clarity_api_daily_usage', 'SELECT')
    or has_table_privilege('authenticated', 'public.clarity_api_daily_usage', 'SELECT')
  then
    raise exception 'A browser role can access private Clarity analytics data';
  end if;
end;
$verify$;

alter table public.bookings
  add column if not exists attribution_ref text;

comment on column public.bookings.attribution_ref is
  'Integritetssäker hänvisningskategori. Rått ref-värde eller kundidentitet sparas aldrig.';
