create table if not exists public.booking_capacity_overrides (
  id bigint generated by default as identity primary key,
  booking_date date not null unique,
  reason text,
  created_at timestamp with time zone not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.booking_capacity_overrides enable row level security;
grant select, insert, update, delete on public.booking_capacity_overrides to authenticated;
grant usage, select on sequence public.booking_capacity_overrides_id_seq to authenticated;

create policy "booking admins manage capacity overrides"
on public.booking_capacity_overrides
for all to authenticated
using (private.is_booking_admin())
with check (private.is_booking_admin());

-- Replace the one-booking-per-day index with the same guard plus an explicit
-- admin capacity override. This keeps normal customer bookings protected.
drop index if exists public.bookings_one_active_date_idx;

create or replace function private.enforce_booking_day_capacity()
returns trigger
language plpgsql
security definer
set search_path = pg_catalog, public
as $$
begin
  if new.status in ('pending', 'confirmed')
    and new.booking_date >= date '2026-07-15'
    and not exists (select 1 from public.booking_capacity_overrides where booking_date = new.booking_date)
    and exists (
      select 1 from public.bookings
      where booking_date = new.booking_date
        and status in ('pending', 'confirmed')
        and id <> new.id
    )
  then
    raise exception 'booking_date_unavailable' using errcode = 'unique_violation';
  end if;
  return new;
end;
$$;

drop trigger if exists enforce_booking_day_capacity on public.bookings;
create trigger enforce_booking_day_capacity
before insert or update of booking_date, status on public.bookings
for each row execute function private.enforce_booking_day_capacity();
