create table if not exists public.discount_codes (
  id bigint generated by default as identity primary key,
  code text not null check (code = upper(trim(code)) and code ~ '^[A-Z0-9_-]{3,32}$'),
  discount_type text not null check (discount_type in ('percentage', 'fixed')),
  discount_value integer not null check (discount_value > 0),
  active boolean not null default true,
  starts_at timestamptz,
  expires_at timestamptz,
  max_uses integer check (max_uses is null or max_uses > 0),
  times_used integer not null default 0 check (times_used >= 0),
  created_at timestamptz not null default now(),
  created_by uuid references auth.users(id) on delete set null,
  constraint discount_codes_date_order check (expires_at is null or starts_at is null or expires_at > starts_at),
  constraint discount_codes_percentage_max check (discount_type <> 'percentage' or discount_value <= 100)
);

create unique index if not exists discount_codes_normalized_code_idx
  on public.discount_codes (upper(code));

alter table public.discount_codes enable row level security;

grant select, insert, update, delete on public.discount_codes to authenticated;
grant usage, select on sequence public.discount_codes_id_seq to authenticated;

drop policy if exists "booking admins can read discount codes" on public.discount_codes;
create policy "booking admins can read discount codes"
on public.discount_codes
for select
to authenticated
using (private.is_booking_admin());

drop policy if exists "booking admins can insert discount codes" on public.discount_codes;
create policy "booking admins can insert discount codes"
on public.discount_codes
for insert
to authenticated
with check (private.is_booking_admin());

drop policy if exists "booking admins can update discount codes" on public.discount_codes;
create policy "booking admins can update discount codes"
on public.discount_codes
for update
to authenticated
using (private.is_booking_admin())
with check (private.is_booking_admin());

drop policy if exists "booking admins can delete discount codes" on public.discount_codes;
create policy "booking admins can delete discount codes"
on public.discount_codes
for delete
to authenticated
using (private.is_booking_admin());

alter table public.bookings
  add column if not exists original_price integer,
  add column if not exists discount_amount integer,
  add column if not exists discount_code text,
  add column if not exists discount_code_id bigint references public.discount_codes(id) on delete set null;

comment on table public.discount_codes is 'Rabattkoder som administreras i adminvyn och valideras i Edge Functions.';
comment on column public.discount_codes.discount_value is 'Procenttal för percentage eller helt antal kronor för fixed.';
comment on column public.discount_codes.max_uses is 'Max antal användningar. Null betyder obegränsat.';
comment on column public.bookings.original_price is 'Ordinarie pris efter RUT men före rabatt, i hela kronor.';
comment on column public.bookings.discount_amount is 'Avdragen rabatt i hela kronor.';
comment on column public.bookings.discount_code is 'Normaliserad kod sparad som historisk ögonblicksbild.';

create or replace function public.consume_discount_code(p_code text, p_original_price integer)
returns table (
  discount_code_id bigint,
  normalized_code text,
  discount_type text,
  discount_value integer,
  discount_amount integer,
  final_price integer
)
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  selected_code public.discount_codes%rowtype;
  calculated_discount integer;
begin
  if p_original_price is null or p_original_price <= 0 then
    raise exception 'invalid_original_price' using errcode = '22023';
  end if;

  select *
  into selected_code
  from public.discount_codes
  where upper(code) = upper(trim(p_code))
    and active = true
    and (starts_at is null or starts_at <= now())
    and (expires_at is null or expires_at > now())
    and (max_uses is null or times_used < max_uses)
  for update;

  if not found then
    raise exception 'invalid_discount_code' using errcode = 'P0001';
  end if;

  calculated_discount := case
    when selected_code.discount_type = 'percentage'
      then round(p_original_price * selected_code.discount_value / 100.0)::integer
    else selected_code.discount_value
  end;
  calculated_discount := least(greatest(calculated_discount, 0), greatest(p_original_price - 1, 0));

  update public.discount_codes
  set times_used = times_used + 1
  where id = selected_code.id;

  return query select
    selected_code.id,
    upper(trim(selected_code.code)),
    selected_code.discount_type,
    selected_code.discount_value,
    calculated_discount,
    p_original_price - calculated_discount;
end;
$$;

revoke all on function public.consume_discount_code(text, integer) from public;
revoke all on function public.consume_discount_code(text, integer) from anon;
revoke all on function public.consume_discount_code(text, integer) from authenticated;
grant execute on function public.consume_discount_code(text, integer) to service_role;
