create table if not exists public.booking_blocked_dates (
  id bigint generated by default as identity primary key,
  blocked_date date not null unique,
  reason text,
  created_at timestamp with time zone not null default now(),
  created_by uuid references auth.users(id) on delete set null
);

alter table public.booking_blocked_dates enable row level security;

grant select, insert, update, delete on public.booking_blocked_dates to authenticated;
grant usage, select on sequence public.booking_blocked_dates_id_seq to authenticated;

drop policy if exists "booking admins can read blocked dates" on public.booking_blocked_dates;
create policy "booking admins can read blocked dates"
on public.booking_blocked_dates
for select
to authenticated
using (private.is_booking_admin());

drop policy if exists "booking admins can insert blocked dates" on public.booking_blocked_dates;
create policy "booking admins can insert blocked dates"
on public.booking_blocked_dates
for insert
to authenticated
with check (private.is_booking_admin());

drop policy if exists "booking admins can update blocked dates" on public.booking_blocked_dates;
create policy "booking admins can update blocked dates"
on public.booking_blocked_dates
for update
to authenticated
using (private.is_booking_admin())
with check (private.is_booking_admin());

drop policy if exists "booking admins can delete blocked dates" on public.booking_blocked_dates;
create policy "booking admins can delete blocked dates"
on public.booking_blocked_dates
for delete
to authenticated
using (private.is_booking_admin());

comment on table public.booking_blocked_dates is 'Datum som admin har spärrat från bokning, till exempel semester eller fullbokade dagar utanför bokningssystemet.';
comment on column public.booking_blocked_dates.blocked_date is 'Datumet som inte ska kunna bokas.';
comment on column public.booking_blocked_dates.reason is 'Intern orsak, till exempel semester.';
